# Generated by Django 5.0.4 on 2024-05-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
