# Generated by Django 5.0.4 on 2024-05-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.comuna'),
        ),
    ]
